server:
  port: 8080
  servlet:
    context-path: /im_bird_sys

spring:
  profiles:
    active: dev # 环境设置
  application:
      name: service-edu # 服务名
  datasource: # mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat?serverTimezone=GMT%2B8
    username: root
    password: 1019726565
    filters: stat
    initial-size: 2
    max-idle: 10
    min-idle: 1
    max-active: 20
    max-wait: 60000
    time-between-evict-runs-millis: 60000
    min-evictable-time-millis: 300000
    validation-query: SELECT 'x'
    test-while-idle: true
    test-on-borrow: false
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
# ===================================================================
# 分布式文件系统FDFS配置
# ===================================================================
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
    - 172.17.9.194:22122